import 'dart:convert';

/// Represents a single journal entry persisted in SQLite.
class JournalEntry {
  const JournalEntry({
    this.id,
    required this.title,
    required this.content,
    required this.date,
    required this.mood,
    this.aiSummary,
    this.aiSentiment,
    this.aiTakeaways,
    this.aiReflectionPrompt,
  });

  /// SQLite auto-increment primary key. `null` for unsaved entries.
  final int? id;

  final String title;
  final String content;
  final DateTime date;

  /// Free-form mood label, e.g. "😊 Happy". See [MoodPresets].
  final String mood;

  /// Two-sentence summary generated by OpenAI.
  final String? aiSummary;

  /// Categorical dominant emotion, e.g. "Grateful", "Anxious".
  final String? aiSentiment;

  /// Three key insights extracted by OpenAI.
  final List<String>? aiTakeaways;

  /// Personalized follow-up question for deep self-reflection.
  final String? aiReflectionPrompt;

  /// The emoji portion of a mood label, e.g. "😊 Happy" -> "😊".
  String get moodEmoji => mood.isEmpty ? '' : mood.split(' ').first;

  /// The text portion of a mood label, e.g. "😊 Happy" -> "Happy".
  String get moodLabel => mood.isEmpty ? '' : mood.split(' ').skip(1).join(' ');

  /// Whether this entry has been analyzed by the AI reflection engine.
  bool get hasAiReflection =>
      aiSummary != null ||
      aiSentiment != null ||
      (aiTakeaways != null && aiTakeaways!.isNotEmpty) ||
      aiReflectionPrompt != null;

  Map<String, dynamic> toMap() => {
        'id': id,
        'title': title,
        'content': content,
        'date': date.toIso8601String(),
        'mood': mood,
        'ai_summary': aiSummary,
        'ai_sentiment': aiSentiment,
        'ai_takeaways': aiTakeaways == null
            ? null
            : jsonEncode(aiTakeaways),
        'ai_reflection_prompt': aiReflectionPrompt,
      };

  factory JournalEntry.fromMap(Map<String, dynamic> map) {
    List<String>? takeaways;
    final raw = map['ai_takeaways'] as String?;
    if (raw != null && raw.isNotEmpty) {
      try {
        final decoded = jsonDecode(raw);
        if (decoded is List) {
          takeaways = decoded.map((e) => e.toString()).toList();
        }
      } on FormatException {
        takeaways = null;
      }
    }

    DateTime? parsedDate;
    final dateRaw = map['date'] as String?;
    if (dateRaw != null && dateRaw.isNotEmpty) {
      parsedDate = DateTime.tryParse(dateRaw);
    }

    return JournalEntry(
      id: map['id'] as int?,
      title: (map['title'] as String?) ?? '',
      content: (map['content'] as String?) ?? '',
      date: parsedDate ?? DateTime.now(),
      mood: (map['mood'] as String?) ?? '',
      aiSummary: map['ai_summary'] as String?,
      aiSentiment: map['ai_sentiment'] as String?,
      aiTakeaways: takeaways,
      aiReflectionPrompt: map['ai_reflection_prompt'] as String?,
    );
  }

  JournalEntry copyWith({
    int? id,
    String? title,
    String? content,
    DateTime? date,
    String? mood,
    String? aiSummary,
    String? aiSentiment,
    List<String>? aiTakeaways,
    String? aiReflectionPrompt,
  }) =>
      JournalEntry(
        id: id ?? this.id,
        title: title ?? this.title,
        content: content ?? this.content,
        date: date ?? this.date,
        mood: mood ?? this.mood,
        aiSummary: aiSummary ?? this.aiSummary,
        aiSentiment: aiSentiment ?? this.aiSentiment,
        aiTakeaways: aiTakeaways ?? this.aiTakeaways,
        aiReflectionPrompt: aiReflectionPrompt ?? this.aiReflectionPrompt,
      );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JournalEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          content == other.content &&
          date == other.date &&
          mood == other.mood &&
          aiSummary == other.aiSummary &&
          aiSentiment == other.aiSentiment &&
          _listEquals(aiTakeaways, other.aiTakeaways) &&
          aiReflectionPrompt == other.aiReflectionPrompt;

  @override
  int get hashCode => Object.hash(
        id,
        title,
        content,
        date,
        mood,
        aiSummary,
        aiSentiment,
        aiReflectionPrompt,
      );

  static bool _listEquals(List<String>? a, List<String>? b) {
    if (identical(a, b)) return true;
    if (a == null || b == null) return a == null && b == null;
    if (a.length != b.length) return false;
    for (var i = 0; i < a.length; i++) {
      if (a[i] != b[i]) return false;
    }
    return true;
  }
}

/// Preset mood options offered by the [MoodSelector] widget.
abstract class MoodPresets {
  static const List<String> moods = [
    '😊 Happy',
    '😔 Anxious',
    '🌿 Calm',
    '🔥 Motivated',
    '💤 Tired',
  ];

  static const Map<String, String> emojiByMood = {
    '😊 Happy': '😊',
    '😔 Anxious': '😔',
    '🌿 Calm': '🌿',
    '🔥 Motivated': '🔥',
    '💤 Tired': '💤',
  };

  static String emojiFor(String mood) => emojiByMood[mood] ?? '📝';
}